# pubspec.yaml
name: krakencase
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.1.2

  # Network
  chopper: ^6.1.4

  # JSON Serialization
  json_annotation: ^4.8.1

  # Routing
  auto_route: ^5.0.4

  # Either Type
  either_dart: ^0.4.0

  # Equatable
  equatable: ^2.0.5

  # Firebase Crashlytics
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9

  #Hide Keys
  flutter_dotenv: ^5.1.0

  # Other Packages
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  auto_route_generator: ^5.0.3
  chopper_generator: ^6.0.3
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.3
  mockito: ^5.4.0
  bloc_test: ^9.1.7
  network_image_mock: ^2.0.1


flutter:
  uses-material-design: true

  assets:
  #Localization assets
    - assets/.env

scripts:
  build_runner_delete_conflict: fvm dart run build_runner build --delete-conflicting-outputs
  build_runner_build: fvm flutter pub run build_runner build

